micronaut:
  application:
    name: dummyapi

  datasources:
    default:
      url: jdbc:mysql://localhost:3307/dummyapi
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: ''
      schema-generate: CREATE_DROP
      dialect: MYSQL