micronaut:
  application:
    name: dummyapi

datasources:
  default:
    url: jdbc:mysql://localhost:3306/dummyapi
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
